const TYPE = {
// actions
AC: {
    SET_INFO: 'SET_INFO',
    GET_USER_LIST: 'GET_USER_LIST',
    GET_USER_GROUP: 'GET_USER_GROUP',
    SET_DELETE_USER: 'SET_DELETE_USER',
    SET_UPDATE_USER: 'SET_UPDATE_USER',
    GET_USER_PROFILE: 'GET_USER_PROFILE',
    SET_USER_LOCATION: 'SET_USER_LOCATION',
    CHANGE_USER_PASSWORD: 'CHANGE_USER_PASSWORD',
    GET_USER_CLEAN_ROUTE_TREE: 'GET_USER_CLEAN_ROUTE_TREE',
},

// mutations
MU: {
    SET_INFO: 'SET_INFO',
    SET_TREE: 'SET_TREE',
    SET_UPDATE_USER: 'SET_UPDATE_USER',
    SET_USER_LIST: 'SET_USER_LIST',
    SET_USER_GROUP: 'SET_USER_GROUP',
    SET_USER_LOCATION: 'SET_USER_LOCATION',
},

// getters
GET: {
    IS_SADMIN: 'IS_SADMIN',
    MY_INFO: 'MY_INFO',
    USER_TREE: 'USER_TREE',
    USER_LIST: 'USER_LIST',
    USER_GROUP: 'USER_GROUP',
    USER_GROUP_BY_ID: 'USER_GROUP_BY_ID',
    SET_USER_LOCATION: 'SET_USER_LOCATION',
    USER_MENU_SETTING: 'USER_MENU_SETTING'
}

}

export default TYPE
