const TYPE = {
  // actions
  AC: {
    UPDATE_GROUP: 'UPDATE_GROUP',
    DELETE_GROUP: 'DELETE_GROUP',
    ADD_NEW_GROUP: 'ADD_NEW_GROUP',
    GET_GROUP_LIST: 'GET_GROUP_LIST',
    GET_GROUP_BY_ID: 'GET_GROUP_BY_ID',
    GET_GROUP_GARAGE: 'GET_GROUP_GARAGE',
    GET_GROUP_CHARGE_STATION: 'GET_GROUP_CHARGE_STATION',
    SET_GROUP_GARAGE: 'SET_GROUP_GARAGE',
    SET_GROUP_CHARGE_STATION: 'SET_GROUP_CHARGE_STATION',
    SET_USER_GROUP: 'SET_USER_GROUP',
    SET_VEHICLE_GROUP: 'SET_VEHICLE_GROUP',
    GET_GROUP_ROUTE_LIST: "GET_GROUP_ROUTE_LIST",
    ADD_GROUP_ROUTE: "ADD_GROUP_ROUTE",
    UPDATE_GROUP_ROUTE: "UPDATE_GROUP_ROUTE",
    DELETE_GROUP_ROUTE: "DELETE_GROUP_ROUTE",
    DEL_GROUP_ROUTE_DETAIL: "DEL_GROUP_ROUTE_DETAIL",
    GET_GROUP_ROUTE_DETAIL: "GET_GROUP_ROUTE_DETAIL",
    SET_GROUP_ROUTE_DETAIL: "SET_GROUP_ROUTE_DETAIL",
  },
  
  // mutations
  MU: {
    SET_GROUP_LIST: 'SET_GROUP_LIST',
    SET_NEW_GROUP: 'SET_NEW_GROUP',
    SET_DELETE_GROUP: 'SET_DELETE_GROUP',
    SET_UPDATE_GROUP: 'SET_UPDATE_GROUP',
    SET_UPDATE_GROUP_DETAIL: 'SET_UPDATE_GROUP_DETAIL',
    SET_GROUP_ROUTE_LIST: 'SET_GROUP_ROUTE_LIST',
    SET_GROUP_ROUTE_DETAIL: 'SET_GROUP_ROUTE_DETAIL',
    SET_DELETE_GROUP_ROUTE_DETAIL: 'SET_DELETE_GROUP_ROUTE_DETAIL',

    
  },
  
  // getters
  GET: {
    //array list
    GROUP_LIST: 'GROUP_LIST',
    GROUP_GARAGE: 'GROUP_GARAGE',
    GROUP_CHARGE: 'GROUP_CHARGE',
    GROUP_ROUTE: 'GROUP_ROUTE',
    GROUP_USER: 'GROUP_USER',
    GROUP_VEHICLE: 'GROUP_VEHICLE',
    //map
    GROUP_ROUTE_MAP: 'GROUP_ROUTE_MAP',
    GROUP_GARAGE_MAP: 'GROUP_GARAGE_MAP',
    GROUP_CHARGE_MAP: 'GROUP_CHARGE_MAP',
    GROUP_VEHICLE_MAP: 'GROUP_VEHICLE_MAP',
    GROUP_ROUTE_DETAIL: 'GROUP_ROUTE_DETAIL'
  }
}
  
export default TYPE
  