const TYPE = {
  // actions
  AC: {
    GET_VEHICLE_LIST: 'GET_VEHICLE_LIST',
    GET_VEHICLE_FOD: 'GET_VEHICLE_FOD',
    GET_VEHICLE_GROUP: 'GET_VEHICLE_GROUP',
    GET_VEHICLE_TYPES: 'GET_VEHICLE_TYPES',
    SET_UPDATE_VEHICLE: 'SET_UPDATE_VEHICLE',
    SET_DELETE_VEHICLE: 'SET_DELETE_VEHICLE',
    SET_REGISTER_VEHICLE: 'SET_REGISTER_VEHICLE'
  },
  
  // mutations
  MU: {
    SET_VEHICLE_LIST: 'SET_VEHICLE_LIST',
    SET_VEHICLE_FOD: 'SET_VEHICLE_FOD',
    SET_UPDATE_VEHICLE: 'SET_UPDATE_VEHICLE',
    SET_VEHICLE_GROUP: 'SET_VEHICLE_GROUP',
    SET_VEHICLE_TYPES: 'SET_VEHICLE_TYPES',
  },
  
  // getters
  GET: {
    VEHICLE_LIST: 'VEHICLE_LIST',
    VEHICLE_FOD: 'VEHICLE_FOD',
    VEHICLE_TYPES: 'VEHICLE_TYPES'
  }
}
  
export default TYPE
  